### ISSUE TITLE
Before each update, reflector should be called.

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#17]
In the wiki there is an article on how to use reflector to update the mirror list everytime you perform an update: [arch-wiki/reflector](https://wiki.archlinux.org/index.php/Reflector#Pacman_Hook)

**Comment by NOhs** [comment]
Implemented in d9f615896cd2277a435fea4000a49e44db473e12

**Comment by GPMueller** [comment]
Has this been tested? I guess we could now merge this into master.

**Comment by GPMueller** [comment]
Merged into master with 00faa6ca77060c954cebd89e8e16306695373b7d.
