### ISSUE TITLE
AUR-packages need to be set according to user input

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#18]
see also #14

**Comment by NOhs** [comment]
Should be resolved with e98fbf2a3f293fec9b1555c16e5ef7d26102baad

**Comment by GPMueller** [comment]
Merged into master with ab16e6a1762641dd95aca60004c9ce61f0062632. However, currently a bug prevents aura from installing packages:
![934f240b-b819-4f17-8b88-ca5902b126cb](https://cloud.githubusercontent.com/assets/20167491/26038149/dd7fa52a-3901-11e7-883c-72f1f47031a8.jpg)
Note that file contents of aurPackageList.txt is as expected:
![2755a1b2-0643-4133-9a68-99975118d9c4](https://cloud.githubusercontent.com/assets/20167491/26038155/fee8d98e-3901-11e7-807d-8c3f0304ff10.jpg)

**Comment by GPMueller** [comment]
Currently cannot be resolved due to #43.

**Comment by GPMueller** [comment]
Seems to be working correctly.
