### ISSUE TITLE
Warnings during setup packages

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#21]
The following warnings/(errors?) appear during 02-setup-packages.sh

> line47: break: only meaningful in a `for', `while', or`until' loop
> line52: ...(same message)
> line 87: ...(same message)
> line 166: ...(same message)

**Comment by NOhs** [comment]
And again in setup-timezone.sh line 15

**Comment by GPMueller** [comment]
Fixed in 93756e47c89cfd948c1d6fa362543677d87f28ee
