### ISSUE TITLE
Visual studio code needs xterm for C++ debugging.

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#23]

**Comment by GPMueller** [comment]
See https://github.com/Microsoft/vscode-cpptools/issues/35
They are trying to implement it that vscode does not need gnome terminal or xterm for it's internal debug console.

It seems they have abandoned Konsole as external debug console for vscode...

**Comment by GPMueller** [comment]
I was not able to get vscode to user the internal terminal as debug console in my vbox.
Added xterm to developer gui packages with 99c373ac1c533714a0a8c9925ebc176bf13e70ee.
