### ISSUE TITLE
Silent boot for arch linux

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#24]
I think it would be cool to activate silent boot: https://wiki.archlinux.org/index.php/Silent_boot. Alternatively we could look for an animation.

**Comment by GPMueller** [comment]
Implemented in 79810029580ea5173cd9f624813720b6721ea942
Missing is 1 Message (probably by [fsck](https://wiki.archlinux.org/index.php/Silent_boot#fsck)).
[startx](https://wiki.archlinux.org/index.php/Silent_boot#startx) might print messages in desktop install.

**Comment by NOhs** [comment]
I think this is good enough for me for the moment.
