### ISSUE TITLE
autopep8 should be part of dev packages

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#35]
Autopep8 helps formatting your python code according to many PEP8 guidelines. It is also used by the vscode python plugin. Therefore, I think it would be useful to have it available as part of the dev packages.

**Comment by GPMueller** [comment]
Is the autopep8 package then used from the command line? Personally I would only use such tools from inside vscode. Or is the package needed for the vscode plugin?
If the latter is the case we should absolutely add it.

**Comment by NOhs** [comment]
The package is used inside vscode if you for example right-click in a python document and select format document. vscode then complains that autopep8 is missing

**Comment by NOhs** [comment]
Note this discussion: https://github.com/DonJayamanne/pythonVSCode/issues/808 . Maybe we should wait to see how this develops.

**Comment by GPMueller** [comment]
in the current master version it seems included (see line 45 in 02_packages)
