### ISSUE TITLE
pip for python2

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#36]
It seems that pip is not installed for python2 by default. This is very confusing as this is usually the standard.
If we have `python2`, I suggest we add `python2-pip`

**Comment by NOhs** [comment]
Maybe Arch is trying harder than other distros to move to Python3. I appreciate that. Has any package for Arch that you use really a dependency on python2-pip?

**Comment by GPMueller** [comment]
No it's not needed from my side. However, as long as we have python2 installed in my opinion we should have it installed properly.

**Comment by NOhs** [comment]
Hm, I guess we should. Although this python duality is really ugly.

**Comment by GPMueller** [comment]
Added in b67142e37a51526cff5d03f901092a681d418430.
