### ISSUE TITLE
'abs' package has been deprecated

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#43]
See https://www.archlinux.org/news/deprecation-of-abs/
abs was a dependency of aura and is still listed as such: https://aur.archlinux.org/packages/aura/ this may be a problem (see also https://github.com/aurapm/aura/issues/452)...

**Comment by GPMueller** [comment]
Removed `abs` with 588dec962e10a1bda7a79d012fd9712c13c122ab.
However, aura will currently not yet build without `abs`.
![image](https://cloud.githubusercontent.com/assets/20167491/26287053/40a8c598-3e73-11e7-96e9-39a74b972642.png)

**Comment by fosskers** [comment]
Do you need the abs functionality in Aura? No one has mentioned it (to confirm their usage of it, etc) since we originally put it in years ago.

**Comment by NOhs** [comment]
@fosskers We just use the basic features like `aura -S(yu)(s)` and `aura -A(s)`. And we have some autocomplete packages `zsh` stuff in there. But if `abs` is not needed for this I guess we do not use `abs.`

**Comment by GPMueller** [comment]
Aura has been updated, removing the dependency on `abs`.
