### ISSUE TITLE
Aura: problem with packages installation (possibly in package list)

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#44]
This appeared after the `abs` dependency was removed from aura (see #43). It is unclear if the aura update is related to this problem.
![fec925d6-f5e6-4303-946f-20bc65a86139](https://cloud.githubusercontent.com/assets/20167491/26648881/2ee366c8-4644-11e7-8ede-548ec259afb0.jpg)

Note that aura seems installed correctly, but no aur packages are installed. What was the deal with `aura-bin`?

![image](https://cloud.githubusercontent.com/assets/20167491/26648693/94fde47a-4643-11e7-91ae-c0f35582a9c6.png)

**Comment by GPMueller** [comment]
Maybe this is related to changes made for #18?

**Comment by fosskers** [comment]
We've seen that `invalid byte sequence` before, it usually clears up when your locales are set correctly.

**Comment by GPMueller** [comment]
Thanks for the tip! 
As this appears only in the installer live iso, it's fair to assume that this would then be related to the locale-settings there. @NOhs pointed me to this [bug in arch](https://bugs.archlinux.org/task/49426) which could be the source of the problem.

Unfortunately, it is unclear to me how we should fix this. Also, in that case, I am surprised it never appeared in our installations before.

**Comment by fosskers** [comment]
I hit some issues a while ago while using Haskell's `criterion` library related to locale, and the following fixed it (in my `fish` config, loaded at every shell creation):
```                                                                                          
set -x LANG 'en_US.UTF-8'
set -x LC_ALL 'en_US.UTF-8'
```
I haven't personally seen `invalid byte sequence` in a long time (a year? two years?).

**Comment by GPMueller** [comment]
Added the `set` commands to `user_input.py` with 9265f6856ab951a535c9d1a1e0352359fd8d97ba. Seems to have fixed the problem.
