### ISSUE TITLE
Aura bytesequence error before aur packages installation

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#52]
The `invalid bytesequence` error in the aura installation - seen already in #18 - seeems to have re-appeared.
<img width="533" alt="screen shot 2017-06-17 at 13 42 15" src="https://user-images.githubusercontent.com/20167491/27252610-427b94ae-5363-11e7-8372-4684d7daa7d0.png">
It appears at least for `full`, but possibly also for others **apart from `minimal`**.

**Comment by GPMueller** [comment]
Does not appear on `developer`, `office`, `minimal`.
Appears on `full`, `media`.
The following shows the `media` aurPackageList.txt` which is read in before the installation:
<img width="542" alt="screen shot 2017-06-17 at 15 54 43" src="https://user-images.githubusercontent.com/20167491/27253466-64aef626-5375-11e7-85e4-d81f072ca182.png">
I cannot exclude the possibility that one of the characters is some strange ascii glyph or something, and I don't see what else could be the problem...

The following shows the file contents for `office`:
![image](https://user-images.githubusercontent.com/20167491/27253489-e16e8474-5375-11e7-81b1-03fd4c65ded2.png)
and for `developer`:
![image](https://user-images.githubusercontent.com/20167491/27253644-b6ae2b92-5378-11e7-92bf-e181eb816854.png)

**Comment by fosskers** [comment]
This can happen when the package maintainer has non-ASCII characters in their name listed in the PKGBUILD.

**Comment by GPMueller** [comment]
Fixed for now with 0e0f07b408da54f586f5ff7235f25e28484f6b87 by removing ´nextcloud-client´.
Surely there must be a better way by somehow fixing locale etc. of the live image.

Closing for now.

**Comment by NOhs** [comment]
Will be properly fixed by the merge request #57
