### ISSUE TITLE
Steam is missing

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#54]
To convince ppl of the easy to use nature of this project, I think we should offer at least steam, which is one of the easy ways to game on linux.

**Comment by GPMueller** [comment]
According to https://wiki.archlinux.org/index.php/Steam we would need to
- determine if the device is x86 or x64 (though we could just assume x64)
- install 32bit packages from the multilib repository
- maybe install ttf-liberation or Steam fonts for arial 
- also have EN_US locale generated

However many more errors may occur, which will probably be system-dependent... See https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues

**Comment by GPMueller** [comment]
Since steam ran nicely without additional measures, aside of activating the multilib repo, I think we can just add this package to one of the sets or create an additional `gaming` set.

**Comment by NOhs** [comment]
Agreed

**Comment by GPMueller** [comment]
Was added to `media` packages with ea291cfc4878ce33e8de617dbd974ed1d5142297 and merged with 7759da8198ec11e695964253217a879d7455ab5f.
