### ISSUE TITLE
Replace AURA

### ISSUE THREAD

**Issue by NOhs** [GPMueller/arch-installer#55]
Aura has some severe issues. It does not reliably determine package dependencies and it offers no assistance in adding PGP keys to the trusted list for AUR packages. Instead it just fails.

I tried out Bauerbill which works reliably. But it has some minor annoyances which I am not sure I can change in the settings. Maybe I will also try another package manager. But we should consider to replace AURA for version 1.2.

**Comment by NOhs** [comment]
Ok. Pacaur could be more what we are after. While the author claims it is not for beginners, I find it very easy to use, and very clean.

**Comment by NOhs** [comment]
Ok, so to install as a user is super simple, because it has almost no dependencies.

    pacman -S yajl expac
    git clone https://aur.archlinux.org/cower.git
    cd cower
    makepkg
    pacman -U *.pkg.tar.xz
    cd ..
    git clone https://aur.archlinux.org/pacaur.git
    makepkg
    pacman -U *.pkg.tar.xz
    cd ..
    rm -rf cower pacaur

I will create a feature branch and to replace AURA.

**Comment by GPMueller** [comment]
Are you confident that Pacaur better meets our requirements?
In what way would it be harder to use "as a beginner"?

**Comment by NOhs** [comment]
I have no idea. For me it seems like the easiest to use.
