### ISSUE TITLE
Add htop to packages

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#58]
At the very least this would be good to have when a desktop is not available. A useful tool for viewing cpu and memory usage overall and per process.

**Comment by NOhs** [comment]
Sounds good to me.

**Comment by GPMueller** [comment]
Added with 9672113cf9255994b8b967bfb9c881c84ba6c0d9 on PR #69. Tested and working.

**Comment by GPMueller** [comment]
Merged with 7759da8198ec11e695964253217a879d7455ab5f.
