### ISSUE TITLE
Installation of cower (dependency of pacaur) failing

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#64]
I have no idea why this error would appear now, while earlier tests ran through...
![image](https://user-images.githubusercontent.com/20167491/30130218-c2a5e5ce-9348-11e7-801d-5203b8d215ff.png)

This issue with the PGP key is known and on the [package site](https://aur.archlinux.org/packages/cower/?comments=all), the following is suggested as a solution:

> If you are having problems installing this package due to signature verification, please run the below before running makepkg:
> `gpg --recv-keys --keyserver hkp://pgp.mit.edu 1EB2638FF56C0C53`
> 
> If makepkg still complains after this:
> 1. Ensure you're using makepkg, and not some wrapper.
> 2. Ensure you don't have `GNUPGHOME` set in `/etc/makepkg.conf` or `~/.makepkg.conf`, or that the value of `GNUGPHOME` in `makepkg.conf` matches that which you've run the above gpg command with.
> 3. Ensure that the tarball you downloaded matches the md5sums in the `PKGBUILD`. 
> 
> If you have problems locating pod2man during the build, please figure out where your `PATH` is being overridden. `/etc/profile.d/perlbin.sh` from the perl package will ensure that pod2man is in your `PATH`.
> 
> Kindly do not do the following because of failures in source tarball verification:
> 1) Complain that the package is broken.
> 2) Mark the package out of date.
> Due to the amount of spam I receive, I've been forced to disable notifications for this package.

**Comment by GPMueller** [comment]
Inserting `gpg --recv-keys --keyserver hkp://pgp.mit.edu 1EB2638FF56C0C53` into `package_manager/installPackageManager.sh` indeed fixes this bug, but is that the right approach?

**Comment by NOhs** [comment]
I think you do not need to specify a server most of the times. Maybe try without.

**Comment by GPMueller** [comment]
Fixed with d5ad559752e81988ff0a5d4fb740efd2e4c0a64b.
