### ISSUE TITLE
Add networkmanager to minimal packages

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#66]
https://wiki.archlinux.de/title/Networkmanager
Without it, network configuration is a pain.

Note: it seems `kdeplasma-applets-plasma-nm` is not available anymore...

**Comment by NOhs** [comment]
See https://www.archlinux.org/packages/?name=plasma-nm

**Comment by GPMueller** [comment]
Note: it seems at least `NetworkManager` needs to be started manually after startup. It should be added to autostart:
`systemctl enable NetworkManager`

**Comment by GPMueller** [comment]
`plasma-nm` is part of `plasma-meta` and therefore already installed on our KDE. Installing `networkmanager` activates the taskbar applet.

**Comment by GPMueller** [comment]
Added with 9672113cf9255994b8b967bfb9c881c84ba6c0d9, enabled (systemctl) with 16d6acff8b45584bbddaf0d5160017ebae73f6ab on PR #69 (`update-packages` branch). Tested and working.

**Comment by GPMueller** [comment]
Merged with 7759da8198ec11e695964253217a879d7455ab5f.
