### ISSUE TITLE
tmux

### ISSUE THREAD

**Issue by DanielSchuerhoff** [GPMueller/arch-installer#67]
pacman -S tmux

ist halt ein cooler Terminal Multiplexer, der lightwight ist, fast überall standardmässig dabei ist und joa ...
- multiplexing
- sessions, die man detachen und reattachen kann (über mehrere ssh sessions)

**Comment by GPMueller** [comment]
I am not sure into which bundle this package should go (similar to htop, see #58).

We have the following package bundles (once each for desktop and for server) which can be installed:
- minimal (is always installed)
- developer (optional)
- office (optional)
- media (optional)
- full (installs all package bundles)

**Comment by GPMueller** [comment]
Added with 9672113cf9255994b8b967bfb9c881c84ba6c0d9 on PR #69. Tested and working.

**Comment by GPMueller** [comment]
Merged with 7759da8198ec11e695964253217a879d7455ab5f.
