### ISSUE TITLE
A new pgp key error: libcap, libcap-ng, libaio

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#70]
![image](https://user-images.githubusercontent.com/20167491/30240351-37177fd0-956f-11e7-9465-685d8b690a79.png)
This is likely related to #64.

**Comment by NOhs** [comment]
This might become an issue, we need to find a better way to deal with those keys...

**Comment by GPMueller** [comment]
This happens during the installation of the base packages... I am confused why this appears, I think it is part of the `pacstrap` process?
The libraries which cause the problems are not part of AUR, but part of core and extra.

Shouldn't those packages have no issues with pgp keys etc? What would we need to update?

**Comment by NOhs** [comment]
I read that if your time is not set correctly, you also see these issues? Can you make sure your time is correct? See this discussion for other suggestions, too: https://bbs.archlinux.org/viewtopic.php?id=195139

**Comment by GPMueller** [comment]
Following the thread and adding this key http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xB02854ED753E0F1F solves the problem, but how can this be done properly?
Essentially it is the same problem as with #64 (`cower`).

**Comment by NOhs** [comment]
Have you tried a new installation iso? I am not sure if this is related, but might be worth a shot. because I do not know if pacstrap actually updates the keys. Maybe some of them changed.

**Comment by GPMueller** [comment]
We do not need to upload new isos, we can simply run
```
pacman -Sy
pacman -S archlinux-keyring
```
We should add this to the very start of the installer.
Found it in this thread: https://bbs.archlinux.org/viewtopic.php?id=185915

Unfortunately this won't fix the problem with the `cower` key...

**Comment by NOhs** [comment]
Yes because that's an AUR package. But one key we can manages I guess

**Comment by GPMueller** [comment]
Exactly.
We can manage both through the installer scripts and thus won't have to update the iso for any of these problems.

**Comment by GPMueller** [comment]
Fixed with c7d897296141ee3233cd183b13f0d00a00e641aa.
