### ISSUE TITLE
Autostart packages

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/arch-installer#72]
This issue is meant to track packages we want to autostart, if installed, when the system starts (enabled via `systemctl`).

I suppose we should join together the new `systemctl enable` calls with the calls from `network.py` and `sshd.py` (both then obsolete), as well as `desktop.py`, e.g. into `enable_services.py`.

**Any**:
- [x] dhcpcd
- [x] sshd
- [x] sddm
- [x] NetworkManager

**Desktop**:
- [ ] Steam?

**Server**:
- [x] docker
- [ ] iptables, ip6tables (with a ssh-only sensible default config)

For the server we should decide if we actually want to enable anything by default at all, and if yes then which, since unwanted services would otherwise have to be explicitly disabled by the user.

**Comment by GPMueller** [comment]
Suggestion: ask wether to autostart server packages (i.e. docker images) during installation, if installing server distro. If yes, then use `docker run -d --restart always -name [containername] [servicename]`. Note the restart flag will cause the container to always be started when docker is started.

**Comment by NOhs** [comment]
Does the network manager add anything if no WiFi is installed on the computer?

**Comment by GPMueller** [comment]
> NetworkManager also prefers wired connections over wireless ones, has support for modem connections and certain types of VPN.
> - [link](https://wiki.archlinux.org/index.php/NetworkManager)

In KDE it will give a taskbar widget similar to the one present in Windows.

Also, I'm not sure it's sensible to generally require a wired connection for the installer. We should maybe add it to the next iso (i.e. in the next release). It is extremely inconvenient if it's needed but not present.

Do you have any objections to this package?

**Comment by NOhs** [comment]
No. Sounds very good.

**Comment by GPMueller** [comment]
The autostart of `iptables` etc. are tracked in issue #61.
Merged the rest with PR #69 (7759da8198ec11e695964253217a879d7455ab5f).
